### ISSUE TITLE
Feature request - Language support

### ISSUE THREAD

**Issue by yhojann-cl** [aruljohn/Bible-kjv#7]
Please, separate in one folder by each language using iso code, for collaborations, by example, in spanish:

```
.
├── en
│   └── ...
├── es
│   └── ...
├── fr
│   └── ...
├── LICENSE
└── readme.md
```

**Comment by xinthose** [comment]
I'll see if I can work on this in my fork of this repository.

**Comment by aruljohn** [comment]
> Please, separate in one folder by each language using iso code, for collaborations, by example, in spanish:
> 
> ```
> .
> ├── en
> │   └── ...
> ├── es
> │   └── ...
> ├── fr
> │   └── ...
> ├── LICENSE
> └── readme.md
> ```

Thanks for your request. I'm only hosting the KJV English version in this repo. There are other repositories of the Bible, one for each language. There's a [Telugu version here](https://github.com/aruljohn/Bible-telugu), a [Tamil version here](https://github.com/aruljohn/Bible-tamil) and others which are pending.
